theme: jekyll-theme-minimal
title: Brett Slobodzian's Portfolio
description: >-
  This is Brett's personal portfolio showcasing projects, experience, and skills in Computer Systems Technology.
baseurl: ""
url: "https://slobodzian2279.github.io"

